apiVersion: batch/v1
kind: Job
metadata:
  name: eks-training-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
       - name: test-k8s-train
         image: 453691756499.dkr.ecr.us-west-2.amazonaws.com/tfworld2019:latest
         command: ["python"]
         args: ["cifar10-multi-gpu-horovod.py"]

