apiVersion: kubeflow.org/v1alpha1
kind: MPIJob
metadata:
  name: hvd-test
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: eks-hvd-test
        image: 453691756499.dkr.ecr.us-west-2.amazonaws.com/tfworld2019:latest
        command: ["/bin/sh"]
        args: ["-c", "while true; do ls /training-data/; sleep 5; done"]
        resources:
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - mountPath: /training-data
          name: persistent-storage
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: fsx-claim