apiVersion: v1
kind: Pod
metadata:
  name: fsx-app
spec:
  containers:
  - name: app
    image: 453691756499.dkr.ecr.us-west-2.amazonaws.com/tfworld2019:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do ls /training-data/; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /training-data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: fsx-claim
